import { useState, useRef, useCallback } from 'react'
import { Upload, FileJson, CircleAlert as AlertCircle, CircleCheck as CheckCircle2, Circle as XCircle, Download, Link2, Database } from 'lucide-react'
import { useSoundscape } from '../../soundscape/SoundscapeContext'
import { validateAnalysisImport, matchImportedToRecording, normalizeFilename } from '../../soundscape/audioUtils'
import { downloadValidationReport } from '../../soundscape/exportUtils'
import type { AnalysisImport, ValidationReport, ImportedRecordEntry, Recording } from '../../soundscape/types'

export default function AnalysisTab() {
  const { state, applyImport, matchImported } = useSoundscape()
  const [parsedData, setParsedData] = useState<AnalysisImport | null>(null)
  const [report, setReport] = useState<ValidationReport | null>(null)
  const [, setFileName] = useState('')
  const [parseError, setParseError] = useState<string | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const [importMode, setImportMode] = useState<'replace' | 'merge'>('merge')
  const [manualMatches, setManualMatches] = useState<Record<string, string>>({})
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleFile = useCallback(async (file: File) => {
    setParseError(null)
    setParsedData(null)
    setReport(null)
    setFileName(file.name)

    try {
      const text = await file.text()
      const parsed = JSON.parse(text)
      const validation = validateAnalysisImport(parsed)
      setReport(validation)
      if (validation.valid || validation.validRecordCount > 0) {
        setParsedData(parsed as AnalysisImport)
      }
    } catch (err) {
      console.error('JSON parse error:', err)
      setParseError('Invalid JSON file. The file could not be parsed. Please check the file format and try again.')
    }
  }, [])

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    if (e.dataTransfer.files.length > 0) {
      handleFile(e.dataTransfer.files[0])
    }
  }

  const cancelImport = () => {
    setParsedData(null)
    setReport(null)
    setParseError(null)
    setFileName('')
    setManualMatches({})
  }

  const confirmImport = (validOnly: boolean) => {
    if (!parsedData) return
    let dataToImport = parsedData
    if (validOnly && report) {
      const errorIds = new Set(report.errors.filter((e) => e.recordingId).map((e) => e.recordingId!))
      dataToImport = {
        ...parsedData,
        recordings: parsedData.recordings.filter((r) => !errorIds.has(r.recordingId)),
      }
    }
    applyImport(dataToImport, importMode)
    cancelImport()
  }

  const matched: { imported: ImportedRecordEntry; recording: Recording }[] = []
  const unmatched: ImportedRecordEntry[] = []

  if (parsedData) {
    for (const entry of parsedData.recordings) {
      const manualMatchId = manualMatches[entry.recordingId]
      if (manualMatchId) {
        const rec = state.recordings.find((r) => r.id === manualMatchId)
        if (rec) {
          matched.push({ imported: entry, recording: rec })
          continue
        }
      }
      const rec = matchImportedToRecording(entry, state.recordings)
      if (rec) {
        matched.push({ imported: entry, recording: rec })
      } else {
        unmatched.push(entry)
      }
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="card p-5">
        <h3 className="section-title mb-2">Import Python Analysis Results</h3>
        <p className="text-sm text-charcoal-600 mb-4">
          Import a JSON file generated by the external Python audio-analysis pipeline. The data will be validated and matched to your uploaded recordings.
        </p>

        <div
          onDrop={handleDrop}
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
          onDragLeave={() => setIsDragging(false)}
          className={`flex flex-col items-center justify-center gap-3 rounded-xl border-2 border-dashed p-8 text-center transition-colors ${
            isDragging ? 'border-forest-400 bg-forest-50/50' : 'border-charcoal-200 bg-sand-50'
          }`}
        >
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-forest-50 text-forest-600">
            <FileJson className="h-6 w-6" />
          </div>
          <p className="text-sm font-medium text-charcoal-700">Drag and drop a JSON file here</p>
          <p className="text-xs text-charcoal-400">or</p>
          <button
            onClick={() => fileInputRef.current?.click()}
            className="rounded-lg bg-forest-700 px-4 py-2 text-sm font-medium text-sand-50 hover:bg-forest-800 transition-colors"
          >
            Select JSON file
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept=".json,application/json"
            className="hidden"
            onChange={(e) => {
              if (e.target.files && e.target.files[0]) handleFile(e.target.files[0])
              e.target.value = ''
            }}
          />
        </div>
      </div>

      {parseError && (
        <div className="card p-4 border-rose-200">
          <div className="flex items-start gap-2">
            <XCircle className="h-5 w-5 shrink-0 text-rose-600 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-rose-800">Import failed</p>
              <p className="text-xs text-rose-700 mt-1">{parseError}</p>
            </div>
          </div>
        </div>
      )}

      {report && (
        <div className="card p-5">
          <div className="flex items-center justify-between mb-4">
            <h3 className="section-title">Validation Report</h3>
            <button
              onClick={() => downloadValidationReport(report, 'validation_report.json')}
              className="flex items-center gap-1.5 rounded-md border border-charcoal-200 px-2.5 py-1.5 text-xs font-medium text-charcoal-600 hover:bg-sand-50 transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              Download report
            </button>
          </div>

          <div className="flex flex-wrap gap-3 mb-4">
            <div className="flex items-center gap-2 rounded-lg bg-sand-50 px-3 py-2">
              {report.valid ? <CheckCircle2 className="h-4 w-4 text-forest-600" /> : <AlertCircle className="h-4 w-4 text-amber-600" />}
              <span className="text-sm font-medium text-charcoal-700">
                {report.valid ? 'All records valid' : `${report.errors.length} validation error(s)`}
              </span>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-sand-50 px-3 py-2">
              <span className="text-sm text-charcoal-600">Valid records: <strong className="text-charcoal-800">{report.validRecordCount}</strong></span>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-sand-50 px-3 py-2">
              <span className="text-sm text-charcoal-600">Total records: <strong className="text-charcoal-800">{report.totalRecordCount}</strong></span>
            </div>
          </div>

          {report.errors.length > 0 && (
            <div className="flex flex-col gap-2 mb-4">
              <h4 className="text-xs font-medium uppercase text-rose-600">Errors</h4>
              {report.errors.map((err, i) => (
                <div key={i} className="rounded-lg border border-rose-100 bg-rose-50/50 p-3">
                  <div className="flex items-start gap-2">
                    <AlertCircle className="h-3.5 w-3.5 shrink-0 text-rose-600 mt-0.5" />
                    <div className="text-xs">
                      <p className="font-medium text-rose-800">{err.field}</p>
                      <p className="text-rose-700 mt-0.5">{err.message}</p>
                      <p className="text-charcoal-500 mt-1">
                        Expected: {err.expected} · Actual: {err.actual}
                      </p>
                      {err.recordingId && <p className="text-charcoal-500">Recording ID: {err.recordingId}</p>}
                      <p className="text-forest-700 mt-1">Suggestion: {err.suggestion}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {parsedData && report && (report.valid || report.validRecordCount > 0) && (
        <div className="card p-5">
          <h3 className="section-title mb-4">Import Options</h3>
          <div className="flex flex-col gap-3 mb-4">
            <label className="flex items-center gap-2 text-sm text-charcoal-700">
              <input type="radio" name="importMode" value="merge" checked={importMode === 'merge'} onChange={() => setImportMode('merge')} />
              Merge with existing recordings
            </label>
            <label className="flex items-center gap-2 text-sm text-charcoal-700">
              <input type="radio" name="importMode" value="replace" checked={importMode === 'replace'} onChange={() => setImportMode('replace')} />
              Replace existing project data
            </label>
          </div>

          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => confirmImport(true)}
              className="rounded-lg bg-forest-700 px-4 py-2 text-sm font-medium text-sand-50 hover:bg-forest-800 transition-colors"
            >
              Import valid records ({report.validRecordCount})
            </button>
            {report.errors.length > 0 && (
              <button
                onClick={() => confirmImport(false)}
                className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2 text-sm font-medium text-amber-700 hover:bg-amber-100 transition-colors"
              >
                Import all records (including invalid)
              </button>
            )}
            <button
              onClick={cancelImport}
              className="rounded-lg border border-charcoal-200 px-4 py-2 text-sm font-medium text-charcoal-600 hover:bg-sand-50 transition-colors"
            >
              Cancel import
            </button>
          </div>
        </div>
      )}

      {parsedData && (
        <div className="card p-5">
          <h3 className="section-title mb-4">Record Matching</h3>

          {matched.length > 0 && (
            <div className="mb-4">
              <h4 className="text-xs font-medium uppercase text-forest-700 mb-2">Matched recordings ({matched.length})</h4>
              <div className="flex flex-col gap-2">
                {matched.map(({ imported, recording }) => (
                  <div key={imported.recordingId} className="flex items-center gap-2 rounded-lg border border-forest-100 bg-forest-50/30 px-3 py-2">
                    <Link2 className="h-3.5 w-3.5 text-forest-600" />
                    <span className="text-sm font-medium text-charcoal-800">{imported.recordingId}</span>
                    <span className="text-xs text-charcoal-400">→</span>
                    <span className="text-sm text-charcoal-600">{recording.metadata.name}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {unmatched.length > 0 && (
            <div>
              <h4 className="text-xs font-medium uppercase text-amber-700 mb-2">Unmatched imported records ({unmatched.length})</h4>
              <p className="text-xs text-charcoal-500 mb-3">These imported records could not be automatically matched to uploaded audio. You can match them manually.</p>
              <div className="flex flex-col gap-2">
                {unmatched.map((entry) => (
                  <div key={entry.recordingId} className="flex items-center gap-3 rounded-lg border border-amber-100 bg-amber-50/30 px-3 py-2">
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-charcoal-800">{entry.recordingId}</p>
                      <p className="text-xs text-charcoal-400">{entry.filename ?? 'No filename'} · {entry.habitatCategory}</p>
                    </div>
                    <select
                      value={manualMatches[entry.recordingId] ?? ''}
                      onChange={(e) => {
                        const newMatches = { ...manualMatches, [entry.recordingId]: e.target.value }
                        setManualMatches(newMatches)
                        if (e.target.value) {
                          matchImported(e.target.value, entry.recordingId)
                        }
                      }}
                      className="rounded-md border border-charcoal-200 bg-white px-2 py-1 text-xs"
                    >
                      <option value="">Match to recording...</option>
                      {state.recordings.map((r) => (
                        <option key={r.id} value={r.id}>
                          {r.metadata.name} ({normalizeFilename(r.metadata.filename)})
                        </option>
                      ))}
                    </select>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {state.recordings.filter((r) => r.importedFeatures).length > 0 && (
        <div className="card p-5">
          <h3 className="section-title mb-4">Imported Metrics Summary</h3>
          <div className="flex items-center gap-2 rounded-lg bg-forest-50 px-3 py-2.5">
            <Database className="h-4 w-4 text-forest-600" />
            <span className="text-sm text-forest-800">
              {state.recordings.filter((r) => r.importedFeatures).length} recordings have imported Python pipeline metrics.
            </span>
          </div>
        </div>
      )}
    </div>
  )

  void Upload
}
